/* Auto-generated by parse_sap_pdfs.py — do not edit */
window.DAILY_SNAPSHOT = {
  "generated": "2026-07-01T08:21:17.663495",
  "meta": {
    "date": "06/30/2026",
    "shift": "24H",
    "project": "Spiral Line LR-LDC - API 5L",
    "pipe": "42\" x 0.600\"",
    "coating": "FBE+IFC",
    "crewDay": "A",
    "crewNight": "B",
    "prodSup": "\u2014",
    "qualSup": "\u2014",
    "maintSup": "\u2014",
    "speeds": {
      "extBlast": 0,
      "extCoat": 0,
      "intBlast": 0,
      "intCoat": 0
    }
  },
  "production": {
    "bare": {
      "day": 63,
      "night": 48,
      "total": 111,
      "tgt": 140
    },
    "idCoated": {
      "day": 60,
      "night": 75,
      "total": 135,
      "tgt": 140
    },
    "odTpi": {
      "day": 77,
      "night": 90,
      "total": 167,
      "tgt": 145
    },
    "odCoated": {
      "day": 76,
      "night": 89,
      "total": 165,
      "tgt": 145
    },
    "wipBareId": {
      "total": 237,
      "tgt": 400
    },
    "wipIdOd": {
      "total": 334,
      "tgt": 400
    },
    "directFeedPct": {
      "val": 44.14,
      "tgt": 75
    },
    "idOdFeedPct": {
      "val": 80.61,
      "tgt": 75
    },
    "loadedRail": {
      "day": 77,
      "night": 90,
      "total": 167,
      "tgt": 145
    },
    "odFromGround": {
      "total": 0
    }
  },
  "quality": {
    "ftrOd": 98.18,
    "repairPct": 0.61,
    "rejectPct": 1.21,
    "ftrOdTgt": 96,
    "ftrId": 94.07,
    "idRejectPct": 5.93,
    "ftrIdTgt": 98,
    "repairPipes": 1,
    "rejectPipes": 2,
    "twoPartRepairs": 173,
    "bevel": 1,
    "sample": 2,
    "tape": 0,
    "idRejects": 8,
    "pipeMismatch": 0,
    "pipesToGroundId": 0
  },
  "maintenance": {
    "idDowntimeHrs": 0,
    "odDowntimeHrs": 0,
    "tgt": 85,
    "sapNotif": 0,
    "plannedDt": 0,
    "unplannedDt": 0,
    "forklift": 0,
    "downtimeEvents": []
  }
};
