/* Auto-generated by parse_sap_pdfs.py — do not edit */
window.DAILY_SNAPSHOT = {
  "generated": "2026-09-04T08:08:48.260136",
  "meta": {
    "date": "09/03/2026",
    "shift": "24H",
    "project": "KM MSX",
    "pipe": "42\" x 0.600\" WT",
    "coating": "IFC + FBE",
    "crewDay": "A/C",
    "crewNight": "A/C",
    "prodSup": "Keith W/ Brian R",
    "qualSup": "Tino M/ Jeenesh S",
    "maintSup": "Ravindra Y/ Adam E",
    "speeds": {
      "extBlast": 12,
      "extCoat": 12,
      "intBlast": 9,
      "intCoat": 11
    }
  },
  "production": {
    "bare": {
      "day": 70,
      "night": 53,
      "total": 123,
      "tgt": 140
    },
    "idCoated": {
      "day": 61,
      "night": 70,
      "total": 131,
      "tgt": 140
    },
    "odTpi": {
      "day": 63,
      "night": 61,
      "total": 124,
      "tgt": 145
    },
    "odCoated": {
      "day": 70,
      "night": 65,
      "total": 135,
      "tgt": 145
    },
    "wipBareId": {
      "total": 263,
      "tgt": 400
    },
    "wipIdOd": {
      "total": 141,
      "tgt": 400
    },
    "directFeedPct": {
      "val": 51.22,
      "tgt": 75
    },
    "idOdFeedPct": {
      "val": 100,
      "tgt": 75
    },
    "stripBalanceId": {
      "val": 3,
      "tgt": 20
    },
    "stripBalanceOd": {
      "val": 13,
      "tgt": 20
    },
    "odRepairBalance": {
      "val": 9,
      "tgt": 40
    }
  },
  "quality": {
    "ftrOd": 88.15,
    "repairPct": 5.93,
    "rejectPct": 5.93,
    "ftrOdTgt": 96,
    "ftrId": 100.0,
    "idRejectPct": 0.0,
    "ftrIdTgt": 98,
    "repairPipes": 8,
    "rejectPipes": 8,
    "twoPartRepairs": 279,
    "bevel": 3,
    "sample": 2,
    "tape": 1,
    "repairsLoadout": 0,
    "tpiToGroundSouth": 0,
    "strippingOutput": 3,
    "idRejects": 0,
    "pipeMismatch": 0,
    "pipesToGroundId": 0
  },
  "maintenance": {
    "idDowntimeHrs": 5.42,
    "odDowntimeHrs": 11.42,
    "tgt": 85,
    "sapNotif": 20,
    "plannedDt": 10.06,
    "unplannedDt": 6.33,
    "forklift": 0,
    "downtimeEvents": [
      {
        "desc": "Startup",
        "line": "ID",
        "start": "06:00",
        "stop": "06:30",
        "durMin": 30,
        "shift": "Day",
        "cause": "",
        "sap": "700094127"
      },
      {
        "desc": "pitstop",
        "line": "ID",
        "start": "17:15",
        "stop": "18:00",
        "durMin": 45,
        "shift": "Day",
        "cause": "",
        "sap": "700094138"
      },
      {
        "desc": "Welding on blaster 1 boom crack - runnin",
        "line": "ID",
        "start": "06:30",
        "stop": "07:25",
        "durMin": 55,
        "shift": "Day",
        "cause": "",
        "sap": "30000004725"
      },
      {
        "desc": "Chain misalighment on sensors - carriers",
        "line": "ID",
        "start": "09:20",
        "stop": "09:35",
        "durMin": 15,
        "shift": "Day",
        "cause": "",
        "sap": "30000004726"
      },
      {
        "desc": "Grit valve and Turbine belt adjustment",
        "line": "ID",
        "start": "11:20",
        "stop": "12:05",
        "durMin": 45,
        "shift": "Day",
        "cause": "",
        "sap": "30000004727"
      },
      {
        "desc": "Grit valve and Turbine belt adjustment",
        "line": "ID",
        "start": "13:50",
        "stop": "14:15",
        "durMin": 25,
        "shift": "Day",
        "cause": "",
        "sap": "30000004728"
      },
      {
        "desc": "Startup",
        "line": "ID",
        "start": "18:00",
        "stop": "18:30",
        "durMin": 30,
        "shift": "Night",
        "cause": "",
        "sap": "700094208"
      },
      {
        "desc": "Pitstop",
        "line": "ID",
        "start": "05:25",
        "stop": "06:00",
        "durMin": 35,
        "shift": "Night",
        "cause": "",
        "sap": "700094224"
      },
      {
        "desc": "Head Locked up on 2/Boom cracked on 1",
        "line": "ID",
        "start": "18:30",
        "stop": "19:15",
        "durMin": 45,
        "shift": "Night",
        "cause": "",
        "sap": "30000004746"
      },
      {
        "desc": "Start up",
        "line": "ID",
        "start": "18:00",
        "stop": "18:25",
        "durMin": 25,
        "shift": "Night",
        "cause": "",
        "sap": "700094020"
      },
      {
        "desc": "pitstop",
        "line": "ID",
        "start": "01:05",
        "stop": "01:35",
        "durMin": 30,
        "shift": "Night",
        "cause": "",
        "sap": "700094107"
      },
      {
        "desc": "pitstop",
        "line": "ID",
        "start": "05:20",
        "stop": "06:00",
        "durMin": 40,
        "shift": "Night",
        "cause": "",
        "sap": "700094122"
      },
      {
        "desc": "adjusted long belt on blaster 2",
        "line": "ID",
        "start": "18:50",
        "stop": "19:15",
        "durMin": 25,
        "shift": "Night",
        "cause": "",
        "sap": "30000004722"
      },
      {
        "desc": "Startup",
        "line": "OD",
        "start": "06:00",
        "stop": "06:25",
        "durMin": 25,
        "shift": "Day",
        "cause": "",
        "sap": "700094128"
      },
      {
        "desc": "Final table full - TPI/jeeps",
        "line": "OD",
        "start": "08:00",
        "stop": "09:00",
        "durMin": 60,
        "shift": "Day",
        "cause": "",
        "sap": "700094135"
      },
      {
        "desc": "Final table full - TPI/jeeps",
        "line": "OD",
        "start": "10:55",
        "stop": "12:30",
        "durMin": 95,
        "shift": "Day",
        "cause": "",
        "sap": "700094136"
      },
      {
        "desc": "Final table full - TPI/jeeps",
        "line": "OD",
        "start": "14:40",
        "stop": "16:05",
        "durMin": 85,
        "shift": "Day",
        "cause": "",
        "sap": "700094137"
      },
      {
        "desc": "pitstop",
        "line": "OD",
        "start": "17:00",
        "stop": "18:00",
        "durMin": 60,
        "shift": "Day",
        "cause": "",
        "sap": "700094139"
      },
      {
        "desc": "Startup",
        "line": "OD",
        "start": "18:00",
        "stop": "18:30",
        "durMin": 30,
        "shift": "Night",
        "cause": "",
        "sap": "700094206"
      },
      {
        "desc": "Final Table Backed up due to ID repairs",
        "line": "OD",
        "start": "22:45",
        "stop": "23:15",
        "durMin": 30,
        "shift": "Night",
        "cause": "",
        "sap": "700094207"
      },
      {
        "desc": "Final Table Backed up",
        "line": "OD",
        "start": "04:40",
        "stop": "06:00",
        "durMin": 80,
        "shift": "Night",
        "cause": "",
        "sap": "700094223"
      },
      {
        "desc": "Hole in Powder Room hopper 1 hose",
        "line": "OD",
        "start": "19:50",
        "stop": "20:25",
        "durMin": 35,
        "shift": "Night",
        "cause": "",
        "sap": "30000004742"
      },
      {
        "desc": "Bearing on Blaster 1 auger being replace",
        "line": "OD",
        "start": "23:15",
        "stop": "23:35",
        "durMin": 20,
        "shift": "Night",
        "cause": "",
        "sap": "30000004743"
      },
      {
        "desc": "Bearing on Blaster 1 auger being replace",
        "line": "OD",
        "start": "00:20",
        "stop": "03:05",
        "durMin": 165,
        "shift": "Night",
        "cause": "",
        "sap": "30000004744"
      }
    ]
  }
};
