/* Auto-generated by parse_sap_pdfs.py — do not edit */
window.DAILY_SNAPSHOT = {
  "generated": "2026-09-22T19:44:36.750242",
  "meta": {
    "date": "09/22/2026",
    "shift": "Day",
    "project": "KM MSX",
    "pipe": "42\" x 0.600\" WT",
    "coating": "IFC + FBE",
    "crewDay": "A/C",
    "crewNight": "A/C",
    "prodSup": "Keith W/ Brian R",
    "qualSup": "Tino M/ Jeenesh S",
    "maintSup": "Ravindra Y/ Adam E",
    "speeds": {
      "extBlast": 12,
      "extCoat": 12,
      "intBlast": 9,
      "intCoat": 11
    }
  },
  "production": {
    "bare": {
      "day": 77,
      "night": 0,
      "total": 77,
      "tgt": 140
    },
    "idCoated": {
      "day": 70,
      "night": 0,
      "total": 70,
      "tgt": 140
    },
    "odTpi": {
      "day": 54,
      "night": 0,
      "total": 54,
      "tgt": 145
    },
    "odCoated": {
      "day": 58,
      "night": 0,
      "total": 58,
      "tgt": 145
    },
    "wipBareId": {
      "total": 304,
      "tgt": 400
    },
    "wipIdOd": {
      "total": 124,
      "tgt": 400
    },
    "directFeedPct": {
      "val": 0.0,
      "tgt": 75
    },
    "idOdFeedPct": {
      "val": 0.0,
      "tgt": 75
    },
    "stripBalanceId": {
      "val": 16,
      "tgt": 20
    },
    "stripBalanceOd": {
      "val": 19,
      "tgt": 20
    },
    "odRepairBalance": {
      "val": 16,
      "tgt": 40
    }
  },
  "quality": {
    "ftrOd": 94.83,
    "repairPct": 1.72,
    "rejectPct": 3.45,
    "ftrOdTgt": 96,
    "ftrId": 100.0,
    "idRejectPct": 0.0,
    "ftrIdTgt": 98,
    "repairPipes": 1,
    "rejectPipes": 2,
    "twoPartRepairs": 98,
    "bevel": 0,
    "sample": 1,
    "tape": 0,
    "repairsLoadout": 0,
    "tpiToGroundSouth": 0,
    "strippingOutput": 6,
    "idRejects": 0,
    "pipeMismatch": 0,
    "pipesToGroundId": 0
  },
  "maintenance": {
    "idDowntimeHrs": 2.08,
    "odDowntimeHrs": 7.0,
    "tgt": 85,
    "sapNotif": 7,
    "plannedDt": 9.08,
    "unplannedDt": 0.0,
    "forklift": 0,
    "downtimeEvents": [
      {
        "desc": "plant start up",
        "line": "ID",
        "start": "06:00",
        "stop": "06:35",
        "durMin": 35,
        "shift": "Day",
        "cause": "",
        "sap": "700095542"
      },
      {
        "desc": "pitstop",
        "line": "ID",
        "start": "13:30",
        "stop": "14:30",
        "durMin": 60,
        "shift": "Day",
        "cause": "",
        "sap": "700095545"
      },
      {
        "desc": "final table backed up",
        "line": "ID",
        "start": "15:30",
        "stop": "16:00",
        "durMin": 30,
        "shift": "Day",
        "cause": "",
        "sap": "700095546"
      },
      {
        "desc": "plant start up",
        "line": "OD",
        "start": "06:00",
        "stop": "06:45",
        "durMin": 45,
        "shift": "Day",
        "cause": "",
        "sap": "700095543"
      },
      {
        "desc": "final table backed up north rotator",
        "line": "OD",
        "start": "09:10",
        "stop": "11:00",
        "durMin": 110,
        "shift": "Day",
        "cause": "",
        "sap": "700095547"
      },
      {
        "desc": "jeep and thickness backed up",
        "line": "OD",
        "start": "11:45",
        "stop": "13:30",
        "durMin": 105,
        "shift": "Day",
        "cause": "",
        "sap": "700095548"
      },
      {
        "desc": "final table backed up north rotator",
        "line": "OD",
        "start": "15:20",
        "stop": "18:00",
        "durMin": 160,
        "shift": "Day",
        "cause": "",
        "sap": "700095550"
      }
    ]
  }
};
